import type { BrickPlacement } from './sequencer';

const LDRAW_COLOR_BY_NAME: Record<string, number> = {
  black: 0,
  blue: 1,
  green: 2,
  red: 4,
  brown: 6,
  'light gray': 7,
  'light grey': 7,
  'dark gray': 8,
  'dark grey': 8,
  'light blue': 9,
  'bright green': 10,
  yellow: 14,
  white: 15,
  tan: 19,
  orange: 25,
  magenta: 26,
  lime: 27,
  'dark tan': 28,
  'dark blue': 272,
  'dark green': 288,
  'dark red': 320,
  'dark bluish gray': 72,
  'dark bluish grey': 72,
  'light bluish gray': 71,
  'light bluish grey': 71,
  'reddish brown': 70,
  'medium blue': 73,
  'medium nougat': 150,
  'bright light orange': 191,
  'bright light blue': 212,
  'bright light yellow': 226,
  'dark pink': 5,
  pink: 13,
  'trans-clear': 47,
  'trans clear': 47,
  'trans-red': 36,
  'trans red': 36,
  'trans-blue': 33,
  'trans blue': 33,
  'trans-yellow': 46,
  'trans yellow': 46,
};

export function ldrawColorCode(colorName: string): number {
  const normalized = colorName.trim().toLowerCase();
  if (LDRAW_COLOR_BY_NAME[normalized] !== undefined) return LDRAW_COLOR_BY_NAME[normalized];
  const withoutPrefix = normalized.replace(/^(transparent|trans)[ -]/, 'trans-');
  return LDRAW_COLOR_BY_NAME[withoutPrefix] ?? 7;
}

function transform(rotation: 0 | 90): string {
  // Rotation around LDraw's Y axis.
  return rotation === 90
    ? '0 0 1 0 1 0 -1 0 0'
    : '1 0 0 0 1 0 0 0 1';
}

/**
 * Emits a normal LDraw model whose type-1 lines reference the canonical parts
 * library. Coordinates use 20 LDU per stud and 24 LDU per standard brick.
 */
export function emitLDraw(placements: BrickPlacement[], name: string): string {
  const safeName = name.replace(/[\r\n]+/g, ' ').trim() || 'YelloBricks AI Build';
  const lines = [
    `0 ${safeName}`,
    `0 Name: ${safeName.replace(/[^a-z0-9_-]+/gi, '_')}.ldr`,
    '0 Author: YelloBricks',
    '0 !LDRAW_ORG Model',
    '0 !LICENSE Redistributable under CCAL version 2.0 : see CAreadme.txt',
    '0 // Generated by inventory-constrained BrickGPT-lite sequencing',
  ];

  const ordered = [...placements].sort(
    (a, b) => a.step - b.step || a.z - b.z || a.y - b.y || a.x - b.x,
  );
  let currentStep = ordered[0]?.step ?? 1;

  for (const brick of ordered) {
    if (brick.step !== currentStep) {
      lines.push('0 STEP');
      currentStep = brick.step;
    }
    const x = (brick.x + brick.width / 2) * 20;
    const y = -brick.z * 24;
    const z = (brick.y + brick.depth / 2) * 20;
    lines.push(
      `1 ${ldrawColorCode(brick.colorName)} ${x} ${y} ${z} ${transform(brick.rotation)} ${brick.partNum}.dat`,
    );
  }

  lines.push('0');
  return `${lines.join('\n')}\n`;
}
